# SwiftLint Configuration for FiHikingNetwork

# Included paths
included:
  - FiHikingNetwork
  - FiHikingNetworkTests
  - FiHikingNetworkUITests

# Excluded paths
excluded:
  - Pods
  - DerivedData
  - .build
  - vendor
  - fastlane

# Rules configuration
disabled_rules:
  - trailing_whitespace
  - todo
  - unused_optional_binding

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_string
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule customization
line_length:
  warning: 120
  error: 140
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 40
  error: 50

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 50

# Custom rules
custom_rules:
  # MARK comments
  mark_comment:
    name: "MARK Comment"
    regex: '^\s*// MARK: - .+$'
    message: "Use 'MARK: - ' for section headers"
    severity: warning

  # No print statements in production code
  no_print:
    name: "No Print Statements"
    regex: '\bprint\('
    match_kinds:
      - comment
      - doccomment
      - identifier
      - keyword
      - number
      - objectliteral
      - parameter
      - placeholder
      - string
      - typeidentifier
    message: "Use Logger instead of print() statements"
    severity: warning

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_import
